### ISSUE TITLE
iarbuild tries to create /.iar directory but it lacks permission; segmentation fault

### ISSUE THREAD

**Issue by chris-laplante** [IARSystems/bx-docker#22]
Using IAR build tools 9.30.1 for ARM.

When I try to run 'iarbuild' (even without arguments), it prints nothing and just exits. What's happening is that it is trying to create a /.iar directory but can't because it is running as UID 1000, so it just segfaults.

gdb trace:

```gdb
Reading symbols from /opt/iarsystems/bxarm/common/bin/iarbuild...
(No debugging symbols found in /opt/iarsystems/bxarm/common/bin/iarbuild)
(gdb) run
Starting program: /opt/iarsystems/bxarm-9.30.1/common/bin/iarbuild 
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007f9f2965d7e0 in IfPersistentStorage::operator IfPersistentStorageI&() const () from /opt/iarsystems/bxarm-9.30.1/common/bin/libIdeFrameworkX_shared.so
(gdb) bt
#0  0x00007f9f2965d7e0 in IfPersistentStorage::operator IfPersistentStorageI&() const () from /opt/iarsystems/bxarm-9.30.1/common/bin/libIdeFrameworkX_shared.so
#1  0x00007f9f29666e69 in If::TraceLog(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /opt/iarsystems/bxarm-9.30.1/common/bin/libIdeFrameworkX_shared.so
#2  0x00007f9f29668f30 in If::ScopedLogTask::ScopedLogTask(char const*) () from /opt/iarsystems/bxarm-9.30.1/common/bin/libIdeFrameworkX_shared.so
#3  0x00007f9f29bd776a in PmiToolChainManager::Initialize() () from /opt/iarsystems/bxarm-9.30.1/common/bin/libProjectManagerEngine.so
#4  0x00007f9f29b47e35 in PmToolChainManager::Instance() () from /opt/iarsystems/bxarm-9.30.1/common/bin/libProjectManagerEngine.so
#5  0x000055b4e949e393 in wmain(int, wchar_t**, wchar_t**) ()
#6  0x000055b4e9497d63 in main ()
```

strace:
```
...
getrandom("\xa8\xde\xc9\x15", 4, 0)     = 4
getrandom("\x2b\xee\xf1\xbf", 4, 0)     = 4
getrandom("\xab\x91\xd4\x8a", 4, 0)     = 4
uname({sysname="Linux", nodename="laplante-lm-19", ...}) = 0
readlink("/proc/self/exe", "/opt/iarsystems/bxarm-9.30.1/com"..., 4096) = 48
stat("/.iar", 0x7ffcdd7a5820)           = -1 ENOENT (No such file or directory)
stat("/.iar", 0x7ffcdd7a57c0)           = -1 ENOENT (No such file or directory)
stat("/", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
mkdir("/.iar", 0777)                    = -1 EACCES (Permission denied)
stat("/.iar", 0x7ffcdd7a56e0)           = -1 ENOENT (No such file or directory)
futex(0x7fa4c8b301e0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x8} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

I was able to fix it by doing `docker exec -it  <CONTAINER> bash` and manually creating /.iar as root.

**Comment by felipe-iar** [comment]
Thanks for reporting this bug.

**Comment by chris-laplante** [comment]
> Thanks for reporting this bug.

Sure thing, thanks for the quick fix :)
